### ISSUE TITLE
Complete Challenge

### ISSUE THREAD

**Issue by Lionex** [Lionex/a-star#1]
Challenge description:

>The objective of the challenge that I am asking of you is to code a simple version of an A* algorithm. The objective (at face value) is to implement A* and send me the code. What I really want to see from you however, is to treat me as if I was a novice programmer and provide the code, a description of A* (according to you), and a guide to running the code. I would also like the code to be fairly well commented so I can step through it and understand what you are doing. Remember that I want to see your abilities to document as well as your thought process and abilities in programming.
>
>If I were doing this, my thought would be to make some kind of class or function that takes in a start and goal and returns an array of edges. I will leave it to you to decide how you are going to implement this and look forward to seeing what you can do!
>
>Please let me know if you have any questions or need clarification. You can also come by and talk to me if you need to. Also, please have this code ready before midnight on Wednesday (4/12), let me know if you cannot.

**TO-DO:** note, not all items have the same priority

- [x] Learn algorithm implementation
- [x] Implement algorithm
- [x] Find a documentation system
- [x] Create documentation
- [x] Fully document README.md with information on running the code
- [x] Create unit tests to validate implementation
